#!/bin/bash
echo "Welcome to the JOTPOT OS (JPOS) installer..."
if [ "$(whoami)" != "root" ]
then
	echo "The installer should be run as root. To run as root, either be logged in as root or put 'sudo' in front of the command to start the installation."
	exit
fi
cd /
function file {
	if [ -f "$1" ] || [ -d "$1" ]
	then
		echo "'$1' already exists, renaming it to $1.old"
		sleep 2
		file "$1.old"
		mv "$1" "$1.old"
	fi
}
file "/JPOS-install"
mkdir JPOS-install
cd JPOS-install
echo "Downloading basic content..."
wget https://www.jotpot.co.uk/experimental/JPOS/installer.sh >/dev/null 2>/dev/null
chmod +x installer.sh
sleep 3
echo "Handing you over..."
sleep 2
./installer.sh
exit