#!/bin/bash

#	
#	JOTPOT OS
#	
#	Copyright (c) 2017 Jacob O'Toole
#	
#	Permission is hereby granted, free of charge, to any person obtaining a copy
#	of this software and associated documentation files (the "Software"), to deal
#	in the Software without restriction, including without limitation the rights
#	to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#	copies of the Software, and to permit persons to whom the Software is
#	furnished to do so, subject to the following conditions:
#	
#	The above copyright notice and this permission notice shall be included in all
#	copies or substantial portions of the Software.
#	
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#	FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#	AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#	LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#	OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#	SOFTWARE.
#	


echo "Welcome to the JOTPOT OS (JPOS) installer..."
if [ "$(whoami)" != "root" ]
then
	echo "The installer should be run as root. To run as root, either be logged in as root or put 'sudo' in front of the command to start the installation."
	exit
fi
cd /
function file {
	if [ -f "$1" ] || [ -d "$1" ]
	then
		echo "'$1' already exists, renaming it to $1.old"
		sleep 2
		file "$1.old"
		mv "$1" "$1.old"
	fi
}
file "/JPOS-install"
mkdir JPOS-install
cd JPOS-install
echo "Downloading basic content..."
wget https://www.jotpot.co.uk/experimental/JPOS/installer.sh >/dev/null 2>/dev/null
chmod +x installer.sh
sleep 3
echo "Handing you over..."
sleep 2
./installer.sh
exit