#!/bin/bash

#	Copyright 2017 Jacob O'Toole
#	
#	Licensed under the Apache License, Version 2.0 (the "License");
#	you may not use this file except in compliance with the License.
#	You may obtain a copy of the License at
#	
#	    http://www.apache.org/licenses/LICENSE-2.0
#	
#	Unless required by applicable law or agreed to in writing, software
#	distributed under the License is distributed on an "AS IS" BASIS,
#	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#	See the License for the specific language governing permissions and
#	limitations under the License.


echo "Welcome to the JOTPOT OS (JPOS) installer..."
if [ "$(whoami)" != "root" ]
then
	echo "The installer should be run as root. To run as root, either be logged in as root or put 'sudo' in front of the command to start the installation."
	exit
fi
cd /
function file {
	if [ -f "$1" ] || [ -d "$1" ]
	then
		echo "'$1' already exists, renaming it to $1.old"
		sleep 2
		file "$1.old"
		mv "$1" "$1.old"
	fi
}
file "/JPOS-install"
mkdir JPOS-install
cd JPOS-install
echo "Downloading basic content..."
wget https://www.jotpot.co.uk/experimental/JPOS/installer.sh >/dev/null 2>/dev/null
chmod +x installer.sh
sleep 3
echo "Handing you over..."
sleep 2
./installer.sh
exit